spring:
  application:
    name: teachers-drawer

  datasource:
    url: jdbc:postgresql://localhost:5432/teachers_drawer
    username: drawer_user
    password: drawer_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create	
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
server:
    port: 8080
jwt:
  secret: teachers-drawer-jwt-secret-key-must-be-at-least-256-bits-long-enough
  access-token-expiration: 900000
  refresh-token-expiration: 604800000

minio:
  endpoint: http://localhost:9000
  access-key: minioadmin
  secret-key: minioadmin123
  bucket-name: teachers-drawer

hwp:
  parser:
    base-url: http://localhost:8001
    timeout-seconds: 60
cors:
  allowed-origins: http://localhost:5173
neis:
  api-key: a29767409ba0402c88f9dfa83ef66a3b
  base-url: https://open.neis.go.kr/hub
kinder:
  api-key: 4d862da49d1840deadb56af202d04700
  base-url: https://e-childschoolinfo.moe.go.kr/api/notice